### ISSUE TITLE
issue #2

### ISSUE THREAD

**Issue by WonDuJin** [WonDuJin/Dusick-Project-A#2]
backend에서 반복문을 활용하여 변수에 code, market의 저장하였고,
이를 문자리터럴을 이용하여 sql문에 사용하여 웹 브라우저로 보내는 과정에서 
print를 실행 할 때에는 반복문이 잘 작동이 되어 콘솔에 출력이 되는데, python runserver.py를 하여 브라우저에 출력 될 때에는 마지막 테이블 1개만 출력이 되는 현상이 있음 

브랜치는 issue_6으로 만들어서 업로드 하였습니다.

**Comment by ghost** [comment]
비동기...?

**Comment by WonDuJin** [comment]
원인 : print는 반복문 내에서 돌아가고 있기 때문에, 콘솔에 반복된 값들이 찍히지만, return을 할 때에는 return이 반복문 밖에 있기 때문에 반복문이 다 작동한 마지막 값만 반환하는 것이 원인이었다.

해결방법 : data_stack = list() 를 사용하여 빈 배열을 만들어준 후 반복문 안에 data_stack.append()를 사용하여 빈 배열에 값을 계속 추가해주고 이 data_stack을 return 하여 해결에 성공하였다.
